/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as Oauth2RedirectRouteImport } from './routes/oauth2/redirect'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicDocsRouteImport } from './routes/_public/docs'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as ProtectedOrganizationsOrgSlugRouteImport } from './routes/_protected/organizations/$orgSlug'
import { Route as ProtectedProjectsOrgSlugProjectSlugRouteImport } from './routes/_protected/_projects/$orgSlug/$projectSlug'
import { Route as ProtectedSchemasOrgSlugProjectSlugSchemaSlugRouteImport } from './routes/_protected/_schemas/$orgSlug/$projectSlug/$schemaSlug'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const Oauth2RedirectRoute = Oauth2RedirectRouteImport.update({
  id: '/oauth2/redirect',
  path: '/oauth2/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDocsRoute = PublicDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrganizationsOrgSlugRoute =
  ProtectedOrganizationsOrgSlugRouteImport.update({
    id: '/organizations/$orgSlug',
    path: '/organizations/$orgSlug',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProjectsOrgSlugProjectSlugRoute =
  ProtectedProjectsOrgSlugProjectSlugRouteImport.update({
    id: '/_projects/$orgSlug/$projectSlug',
    path: '/$orgSlug/$projectSlug',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute =
  ProtectedSchemasOrgSlugProjectSlugSchemaSlugRouteImport.update({
    id: '/_schemas/$orgSlug/$projectSlug/$schemaSlug',
    path: '/$orgSlug/$projectSlug/$schemaSlug',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/docs': typeof PublicDocsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/': typeof PublicIndexRoute
  '/organizations/$orgSlug': typeof ProtectedOrganizationsOrgSlugRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/$orgSlug/$projectSlug': typeof ProtectedProjectsOrgSlugProjectSlugRoute
  '/$orgSlug/$projectSlug/$schemaSlug': typeof ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/docs': typeof PublicDocsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/': typeof PublicIndexRoute
  '/organizations/$orgSlug': typeof ProtectedOrganizationsOrgSlugRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/$orgSlug/$projectSlug': typeof ProtectedProjectsOrgSlugProjectSlugRoute
  '/$orgSlug/$projectSlug/$schemaSlug': typeof ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_public/docs': typeof PublicDocsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/oauth2/redirect': typeof Oauth2RedirectRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/organizations/$orgSlug': typeof ProtectedOrganizationsOrgSlugRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/_projects/$orgSlug/$projectSlug': typeof ProtectedProjectsOrgSlugProjectSlugRoute
  '/_protected/_schemas/$orgSlug/$projectSlug/$schemaSlug': typeof ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/docs'
    | '/verify-email'
    | '/oauth2/redirect'
    | '/'
    | '/organizations/$orgSlug'
    | '/organizations'
    | '/$orgSlug/$projectSlug'
    | '/$orgSlug/$projectSlug/$schemaSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/docs'
    | '/verify-email'
    | '/oauth2/redirect'
    | '/'
    | '/organizations/$orgSlug'
    | '/organizations'
    | '/$orgSlug/$projectSlug'
    | '/$orgSlug/$projectSlug/$schemaSlug'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/$'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_protected/dashboard'
    | '/_public/docs'
    | '/_public/verify-email'
    | '/oauth2/redirect'
    | '/_public/'
    | '/_protected/organizations/$orgSlug'
    | '/_protected/organizations/'
    | '/_protected/_projects/$orgSlug/$projectSlug'
    | '/_protected/_schemas/$orgSlug/$projectSlug/$schemaSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  Oauth2RedirectRoute: typeof Oauth2RedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/oauth2/redirect': {
      id: '/oauth2/redirect'
      path: '/oauth2/redirect'
      fullPath: '/oauth2/redirect'
      preLoaderRoute: typeof Oauth2RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/docs': {
      id: '/_public/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof PublicDocsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/organizations/$orgSlug': {
      id: '/_protected/organizations/$orgSlug'
      path: '/organizations/$orgSlug'
      fullPath: '/organizations/$orgSlug'
      preLoaderRoute: typeof ProtectedOrganizationsOrgSlugRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_projects/$orgSlug/$projectSlug': {
      id: '/_protected/_projects/$orgSlug/$projectSlug'
      path: '/$orgSlug/$projectSlug'
      fullPath: '/$orgSlug/$projectSlug'
      preLoaderRoute: typeof ProtectedProjectsOrgSlugProjectSlugRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_schemas/$orgSlug/$projectSlug/$schemaSlug': {
      id: '/_protected/_schemas/$orgSlug/$projectSlug/$schemaSlug'
      path: '/$orgSlug/$projectSlug/$schemaSlug'
      fullPath: '/$orgSlug/$projectSlug/$schemaSlug'
      preLoaderRoute: typeof ProtectedSchemasOrgSlugProjectSlugSchemaSlugRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOrganizationsOrgSlugRoute: typeof ProtectedOrganizationsOrgSlugRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
  ProtectedProjectsOrgSlugProjectSlugRoute: typeof ProtectedProjectsOrgSlugProjectSlugRoute
  ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute: typeof ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOrganizationsOrgSlugRoute: ProtectedOrganizationsOrgSlugRoute,
  ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  ProtectedProjectsOrgSlugProjectSlugRoute:
    ProtectedProjectsOrgSlugProjectSlugRoute,
  ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute:
    ProtectedSchemasOrgSlugProjectSlugSchemaSlugRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicDocsRoute: typeof PublicDocsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicDocsRoute: PublicDocsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  Oauth2RedirectRoute: Oauth2RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
